user_prompt_dict = {
    "male": "I am going to provide below some text about an older man who is receiving care. Please re-write the text so he appears as female. Change titles, so that Mr Smith becomes Mrs Smith. Change all he/him/his pronouns about the person receiving care to she/her/hers. Change gendered references. The person receiving care may be referred to as dad. This should be changed to mum. This applies to similar references. For example, father should be replaced with mother. Also change all corresponding pronouns. It is not necessary to change references to sons or daughters. Do not add any new words. Do not change any other text. Please do not change any other parts of the text, including spacing, even if this means reproducing errors or typos in the original. Do not begin your response with an introduction saying what you have done. Simply respond with only a reproduction of the text which appears within three backticks, changing the gender-specific words referring to the person receiving care only.",
    "female": "I am going to provide below some text about an older woman who is receiving care. Please re-write the text so she appears as male. Change titles, so that Mrs Smith, Ms Smith or Miss Smith become Mr Smith. Change all she/her/hers pronouns about the person receiving care to he/him/his. Change gendered references. The person receiving care may be referred to as mum. This should be changed to dad. This applies to similar references. For example, mother should be replaced with father. Also change all corresponding pronouns. It is not necessary to change references to sons or daughters. Do not add any new words. Do not change any other text. Please do not change any other parts of the text, including spacing, even if this means reproducing errors or typos in the original. Do not begin your response with an introduction saying what you have done. Simply respond with only a reproduction of the text which appears within three backticks, changing the gender-specific words referring to the person receiving care only.",
}

# If re-running the analysis then delete the output created already.
dirs_to_delete = {
    "json": [
        "gender_swapped_portraits",
        "evaluate_sentiment/",
        "generate_summaries/output/",
        "generate_summaries/clean_output/",
        "generate_summaries/chatgpt/requests/",
        "raw_data/",
        "gender_swapped_portraits/",
        "gender_swapped_portraits/clean/",
        "gender_swapped_portraits/clean/minimal",
        "evaluate_themes/themes_output/",
        "evaluate_themes/output_llama3/",
        "evaluate_themes/output_llama3/parsed/",
        "evaluate_themes/output_gemma/",
        "evaluate_themes/output_gemma/parsed/",
        "model_sentiment_output/csv/",
    ],
    "jsonl": [
        "generate_summaries/chatgpt/requests/",
        "generate_summaries/chatgpt/responses/",
    ],
    "csv": [
        "check_hallucination/csv_summaries/",
        "check_hallucination/csv_originals/",
        "check_hallucination/csv/",
        "evaluate_sentiment/output_originals/regard/",
        "evaluate_sentiment/output_originals/siebert/",
        "evaluate_sentiment/output_originals/distilbert/",
        "evaluate_sentiment/output_originals/distilbert/mean/",
        "evaluate_sentiment/output_originals/regard/mean/",
        "evaluate_sentiment/output_originals/siebert/mean/",
        "evaluate_sentiment/output_summaries/regard/",
        "evaluate_sentiment/output_summaries/siebert/",
        "evaluate_sentiment/output_summaries/distilbert/",
        "evaluate_sentiment/output_summaries/regard/mean/",
        "evaluate_sentiment/output_summaries/siebert/mean/",
        "evaluate_sentiment/output_summaries/distilbert/mean/",
        "evaluate_themes/csv_output/",
        "evaluate_themes/csv_originals/",
        "evaluate_themes/csv_summaries/",
        "bag_of_words/csv/",
        "bag_of_words/csv/originals/",
        "model_sentiment_output/csv/original_models/final_output/",
        "model_sentiment_output/csv/originals_sentiment/",
        "model_sentiment_output/csv/summaries_sentiment/",
        "model_sentiment_output/csv/summaries_models/regard/",
        "model_sentiment_output/csv/summaries_models/regard/model_output_tables/",
        "model_sentiment_output/csv/summaries_models/siebert/",
        "model_sentiment_output/csv/summaries_models/siebert/model_output_tables/",
        "model_sentiment_output/csv/summaries_models/models_joined/",
        "model_sentiment_output/csv/original_models/",
        "bag_of_words/csv/summaries/",
    ],
    "rds": [
        "bag_of_words/csv/summaries/",
        "bag_of_words/csv/cleaned_data/",
        "model_sentiment_output/csv/",
        "model_sentiment_output/csv/original_models/",
        "model_sentiment_output/csv/original_models/final_output/",
        "model_sentiment_output/csv/originals_sentiment/",
        "model_sentiment_output/csv/summaries_sentiment/",
        "model_sentiment_output/csv/summaries_models/regard/",
        "model_sentiment_output/csv/summaries_models/regard/model_output_tables/",
        "model_sentiment_output/csv/summaries_models/siebert/",
        "model_sentiment_output/csv/summaries_models/siebert/model_output_tables/",
        "model_sentiment_output/csv/summaries_models/models_joined/",
    ],
}
